theme: jekyll-theme-minimal
title: Wuxia Scrape
description: Wuxia Scrape is a python application that writes webnovels from NovelFull into text documents on your computer.
logo: /assets/images/logo.png
show_downloads: true
baseurl: /wuxia-scrape
